openapi: 3.0.3
info:
  title: 'SP Info API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  '/api/payment/{profile_id}':
    get:
      summary: 'Show Payment'
      operationId: showPayment
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Payment Management'
      security: []
    parameters:
      -
        in: path
        name: profile_id
        description: 'The ID of the profile.'
        example: placeat
        required: true
        schema:
          type: string
  /api/profiles:
    get:
      summary: ''
      operationId: getApiProfiles
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Profile Management'
      security: []
  '/api/profiles/{id}':
    get:
      summary: 'Show Profile'
      operationId: showProfile
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Profile Management'
      security: []
    put:
      summary: 'Update Profile'
      operationId: updateProfile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Profile Management'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the user.'
                  example: quia
                mobile:
                  type: string
                  description: 'The mobile number of the user.'
                  example: rerum
                pan:
                  type: string
                  description: 'The pan number of the user.'
                  example: mollitia
                address_1:
                  type: string
                  description: 'The address_1 of the user.'
                  example: hic
                address_2:
                  type: string
                  description: 'The address_1 of the user.'
                  example: libero
                city:
                  type: string
                  description: 'The city of the user.'
                  example: tenetur
                state:
                  type: string
                  description: 'The state of the user.'
                  example: blanditiis
                pincode:
                  type: string
                  description: 'The pincode of the user.'
                  example: quam
                bank_name:
                  type: string
                  description: 'The bank name of the user.'
                  example: eos
                account_name:
                  type: string
                  description: 'The account name of the user.'
                  example: autem
                account_no:
                  type: string
                  description: 'The account number of the user.'
                  example: veniam
                ifsc:
                  type: string
                  description: 'The ifsc number of the user.'
                  example: odit
                business_name:
                  type: string
                  description: 'The business_name of the user.'
                  example: accusamus
                gstin:
                  type: string
                  description: 'The gstin of the user.'
                  example: temporibus
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the profile.'
        example: laboriosam
        required: true
        schema:
          type: string
  '/api/profiles/{parent_id}/get_profiles':
    get:
      summary: ''
      operationId: getApiProfilesParent_idGet_profiles
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Profile Management'
      security: []
    parameters:
      -
        in: path
        name: parent_id
        description: 'The ID of the parent.'
        example: tempora
        required: true
        schema:
          type: string
  /api/currnet_month_count:
    get:
      summary: 'Get Current Month Count'
      operationId: getCurrentMonthCount
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Profile Management'
      security: []
  '/api/profiles/{profile_no}/get_ref_profile':
    get:
      summary: ''
      operationId: getApiProfilesProfile_noGet_ref_profile
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: ' Profiles Retrived successfully'
                  data:
                    Profiles: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: ' Profiles Retrived successfully'
                  data:
                    type: object
                    properties:
                      Profiles:
                        type: array
                        example: []
      tags:
        - 'Profile Management'
      security: []
    parameters:
      -
        in: path
        name: profile_no
        description: ''
        example: PeC
        required: true
        schema:
          type: string
  /api/register:
    post:
      summary: 'Register User'
      operationId: registerUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'User Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: btjlhmrztzeqfswbbg
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: hmarquardt@example.com
                mobile:
                  type: string
                  description: 'Must match the regex /^\+(?:\d{1}.'
                  example: '+:8'
                pan:
                  type: string
                  description: 'Must match the regex /^([a-zA-Z]){5}([0-9]){4}([a-zA-Z0-9]){1}?$/.'
                  example: ImbzP2646t
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: ';ZnT^70tY5&{Xz(p'
                password_confirmation:
                  type: string
                  description: ''
                  example: nam
                parent_id:
                  type: string
                  description: ''
                  example: non
                ref_id:
                  type: string
                  description: ''
                  example: et
              required:
                - name
                - email
                - mobile
                - pan
                - password
                - password_confirmation
                - parent_id
                - ref_id
      security: []
  /api/login:
    post:
      summary: 'Login User'
      operationId: loginUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'User Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: zbernhard@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'XyO.."n(pV-!@'
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Logout User'
      operationId: logoutUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'User Management'
      security: []
tags:
  -
    name: 'Payment Management'
    description: ' `'
  -
    name: 'Profile Management'
    description: "\nAPI for Managing Profile data"
  -
    name: 'User Management'
    description: "\nAPI for Managing Users"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
